server:
  port: 9999
  servlet:
    context-path: /msg-producer
kafka:
  producer:
    client:
      id: client_id
    batch:
      size: 10240
    linger:
      ms: 100
    buffer:
      memory: 33554432
    request:
      size: 10485760
  bigdata:
    bootstrap:
      servers: zdbd01:9092,zdbd02:9092,zdbd03:9092
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:/Users/hanwenlong/apps/derby/db/msg-produce;create=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://zdbd02:3306/data_extension?characterEncoding=utf8&useSSL=true
jedis:
  database: 0
  zk:
    connect:
      host: zdbd01:2181,zdbd02:2181,zdbd03:2181
    session:
      timeout: 5000
    proxy:
      dir: /jodis/codis-test1
  session:
    auth: 123456
  connection:
    timeout: 2000
  sotimeout: 2000
  maxTotal: 1000
  maxIdle: 10
  minIdle: 3
  maxWaitMillis: 10000
  softMinEvictableIdleTimeMillis: 5000